import{S as v,a as L,i as l}from"./assets/vendor-Dz6EJGda.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();function m(t){const s=document.querySelector(".gallery"),o=t.map(({webformatURL:a,largeImageURL:e,tags:r,likes:i,views:g,comments:p,downloads:h})=>`
        <li class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${a}" alt="${r}" class="gallery-image" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${i}</p>
            <p><b>Views:</b> ${g}</p>
            <p><b>Comments:</b> ${p}</p>
            <p><b>Downloads:</b> ${h}</p>
          </div>
        </li>
      `).join("");s.insertAdjacentHTML("beforeend",o),new v(".gallery a",{captionsData:"alt",captionDelay:250})}function b(){const t=document.querySelector(".gallery");t.innerHTML=""}const S="49273794-9f9572efe635ab4987a028735",w="https://pixabay.com/api/";async function y(t,s=1,o=15){try{return(await L.get(w,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:o}})).data}catch(a){throw console.error("Error fetching images:",a),a}}const q=document.querySelector("form");document.querySelector(".gallery");const u=document.querySelector(".loader"),c=document.querySelector(".load-more");let d="",n=1;const f=15;c.classList.add("visually-hidden");q.addEventListener("submit",async t=>{if(t.preventDefault(),d=t.target.elements["search-text"].value.trim(),n=1,!d){l.error({title:"Error",message:"Please enter a search query!"});return}b(),c.classList.add("visually-hidden"),u.classList.remove("visually-hidden");try{const s=await y(d,n);s.hits.length===0?l.warning({title:"Oops!",message:"No images found. Try again!"}):(m(s.hits),s.totalHits>f&&c.classList.remove("visually-hidden"))}catch{l.error({title:"Error",message:"Failed to fetch images. Try again later!"})}finally{u.classList.add("visually-hidden")}});c.addEventListener("click",async()=>{n++,u.classList.remove("visually-hidden");try{const t=await y(d,n);m(t.hits),E(),n*f>=t.totalHits&&(c.classList.add("visually-hidden"),l.info({title:"Info",message:"You've reached the end of search results."}))}catch{l.error({title:"Error",message:"Failed to load more images. Try again later!"})}finally{u.classList.add("visually-hidden")}});function E(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
