import{S as v,a as S,i as n}from"./assets/vendor-Dz6EJGda.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();let d;function m(e){const o=document.querySelector(".gallery"),s=e.map(({webformatURL:a,largeImageURL:t,tags:r,likes:i,views:p,comments:b,downloads:L})=>`
        <li class="gallery-item">
          <a href="${t}" class="gallery-link">
            <img src="${a}" alt="${r}" class="gallery-image" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${i}</p>
            <p><b>Views:</b> ${p}</p>
            <p><b>Comments:</b> ${b}</p>
            <p><b>Downloads:</b> ${L}</p>
          </div>
        </li>
      `).join("");o.insertAdjacentHTML("beforeend",s),d?d.refresh():d=new v(".gallery a",{captionsData:"alt",captionDelay:250})}function q(){const e=document.querySelector(".gallery");e.innerHTML=""}function y(){const e=document.querySelector(".loader");e&&e.classList.remove("visually-hidden")}function u(){const e=document.querySelector(".loader");e&&e.classList.add("visually-hidden")}function w(){const e=document.querySelector(".load-more");e&&e.classList.remove("visually-hidden")}function f(){const e=document.querySelector(".load-more");e&&e.classList.add("visually-hidden")}const E="49273794-9f9572efe635ab4987a028735",P="https://pixabay.com/api/";async function g(e,o=1,s=15){try{return(await S.get(P,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:s}})).data}catch(a){throw console.error("Error fetching images:",a),a}}const O=document.querySelector("form");document.querySelector(".gallery");let c="",l=1;const h=15;f();u();O.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements["search-text"].value.trim(),l=1,!c){n.error({title:"Error",message:"Please enter a search query!"});return}q(),f(),y();try{const o=await g(c,l);o.hits.length===0?n.warning({title:"Oops!",message:"No images found. Try again!"}):(m(o.hits),o.totalHits>h&&w())}catch{n.error({title:"Error",message:"Failed to fetch images. Try again later!"})}finally{u()}});document.querySelector(".load-more").addEventListener("click",async()=>{l++,y();try{const e=await g(c,l);m(e.hits),$(),l*h>=e.totalHits&&(f(),n.info({title:"Info",message:"You've reached the end of search results."}))}catch{n.error({title:"Error",message:"Failed to load more images. Try again later!"})}finally{u()}});function $(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
